:source-language: lisp
:uri-flycheck: https://www.flycheck.org/
:uri-eldev: https://github.com/doublep/eldev

= flycheck-eldev

image:https://img.shields.io/badge/license-GPL_3-green.svg[License: GPL 3, link=http://www.gnu.org/licenses/gpl-3.0.txt]
image:https://api.travis-ci.org/flycheck/flycheck-eldev.svg[Build status, link=https://travis-ci.org/flycheck/flycheck-eldev]

Make {uri-flycheck}[Flycheck] use proper dependencies in
{uri-eldev}[Eldev] projects.

For a project to be detected, it must contain file `Eldev` or
`Eldev-local` in its root directory, even if Eldev doesn’t strictly
require that.

== Features

* No additional steps to be performed from the command line, not even
  `eldev prepare`.

* Project dependencies are seen by Flycheck in Emacs.  Similarly, if a
  package is not declared as a dependency of your project, Flycheck
  will complain about unimportable features or undeclared functions.

* Everything is done on-the-fly.  As you edit your project’s
  dependency list in its main `.el` file, added, removed or mistyped
  dependency names immediately become available to Flycheck (there
  might be some delays due to network, as Eldev needs to fetch them
  first).

* Additional test dependencies (see `eldev-add-extra-dependencies`)
  are seen from the test files, but not from the main files.
